import 'package:flutter/material.dart';
import '../config/supabase_client.dart';
import '../models/parking_time_slot_model.dart';

class ParkingTimeSlotService {
  static final _supabase = AppSupabase.client;

  /// Generate time slots based on available hours and rental mode
  static List<ParkingTimeSlot> generateTimeSlots({
    required String parkingSpaceId,
    required TimeOfDay availableFrom,
    required TimeOfDay availableTo,
    required String rentalMode,
  }) {
    final List<ParkingTimeSlot> slots = [];

    switch (rentalMode.toLowerCase()) {
      case 'hourly':
        slots.addAll(
          _generateHourlySlots(
            parkingSpaceId: parkingSpaceId,
            availableFrom: availableFrom,
            availableTo: availableTo,
          ),
        );
        break;
      case 'monthly':
      case 'yearly':
        slots.add(
          _generateFullDurationSlot(
            parkingSpaceId: parkingSpaceId,
            availableFrom: availableFrom,
            availableTo: availableTo,
            rentalMode: rentalMode,
          ),
        );
        break;
    }

    return slots;
  }

  /// Generate hourly slots with 20-minute gaps
  static List<ParkingTimeSlot> _generateHourlySlots({
    required String parkingSpaceId,
    required TimeOfDay availableFrom,
    required TimeOfDay availableTo,
  }) {
    final List<ParkingTimeSlot> slots = [];

    // Convert TimeOfDay to minutes for easier calculation
    int currentMinutes = availableFrom.hour * 60 + availableFrom.minute;
    final endMinutes = availableTo.hour * 60 + availableTo.minute;

    const slotDurationMinutes = 60; // 1 hour
    const gapMinutes = 20; // 20-minute gap

    while (currentMinutes + slotDurationMinutes <= endMinutes) {
      final startTime = _minutesToTimeString(currentMinutes);
      final endTime = _minutesToTimeString(
        currentMinutes + slotDurationMinutes,
      );

      slots.add(
        ParkingTimeSlot(
          id: '', // Will be generated by Supabase
          parkingSpaceId: parkingSpaceId,
          slotStartTime: startTime,
          slotEndTime: endTime,
          status: ParkingTimeSlotStatus.active,
          rentalMode: 'hourly',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
      );

      // Move to next slot start time (current end + gap)
      currentMinutes += slotDurationMinutes + gapMinutes;
    }

    return slots;
  }

  /// Generate single slot for monthly/yearly rental
  static ParkingTimeSlot _generateFullDurationSlot({
    required String parkingSpaceId,
    required TimeOfDay availableFrom,
    required TimeOfDay availableTo,
    required String rentalMode,
  }) {
    return ParkingTimeSlot(
      id: '', // Will be generated by Supabase
      parkingSpaceId: parkingSpaceId,
      slotStartTime: _timeOfDayToString(availableFrom),
      slotEndTime: _timeOfDayToString(availableTo),
      status: ParkingTimeSlotStatus.active,
      rentalMode: rentalMode,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
  }

  /// Convert minutes to HH:mm format
  static String _minutesToTimeString(int minutes) {
    final hour = (minutes ~/ 60) % 24;
    final minute = minutes % 60;
    return '${hour.toString().padLeft(2, '0')}:${minute.toString().padLeft(2, '0')}';
  }

  /// Convert TimeOfDay to HH:mm format
  static String _timeOfDayToString(TimeOfDay time) {
    return '${time.hour.toString().padLeft(2, '0')}:${time.minute.toString().padLeft(2, '0')}';
  }

  /// Save generated slots to Supabase
  static Future<bool> saveTimeSlots(List<ParkingTimeSlot> slots) async {
    try {
      if (slots.isEmpty) return true;

      final slotsData = slots
          .map(
            (slot) => {
              'parking_space_id': slot.parkingSpaceId,
              'slot_start_time': slot.slotStartTime,
              'slot_end_time': slot.slotEndTime,
              'status': slot.status.value,
              'rental_mode': slot.rentalMode,
            },
          )
          .toList();

      await _supabase.from('parking_time_slots').insert(slotsData);

      return true;
    } catch (e) {
      print('Error saving time slots: $e');
      return false;
    }
  }

  /// Get time slots for a parking space
  static Future<List<ParkingTimeSlot>> getTimeSlotsForSpace(
    String parkingSpaceId,
  ) async {
    try {
      final response = await _supabase
          .from('parking_time_slots')
          .select()
          .eq('parking_space_id', parkingSpaceId)
          .order('slot_start_time');

      return (response as List)
          .map((data) => ParkingTimeSlot.fromJson(data))
          .toList();
    } catch (e) {
      print('Error fetching time slots: $e');
      return [];
    }
  }

  /// Toggle slot status between active and paused
  static Future<bool> toggleSlotStatus(
    String slotId,
    ParkingTimeSlotStatus newStatus,
  ) async {
    try {
      await _supabase
          .from('parking_time_slots')
          .update({
            'status': newStatus.value,
            'updated_at': DateTime.now().toIso8601String(),
          })
          .eq('id', slotId);

      return true;
    } catch (e) {
      print('Error toggling slot status: $e');
      return false;
    }
  }

  /// Delete all slots for a parking space (when regenerating)
  static Future<bool> deleteTimeSlotsForSpace(String parkingSpaceId) async {
    try {
      await _supabase
          .from('parking_time_slots')
          .delete()
          .eq('parking_space_id', parkingSpaceId)
          .neq('status', 'booked'); // Don't delete booked slots

      return true;
    } catch (e) {
      print('Error deleting time slots: $e');
      return false;
    }
  }

  /// Regenerate slots (delete existing non-booked slots and create new ones)
  static Future<bool> regenerateTimeSlots({
    required String parkingSpaceId,
    required TimeOfDay availableFrom,
    required TimeOfDay availableTo,
    required String rentalMode,
  }) async {
    try {
      // Delete existing non-booked slots
      await deleteTimeSlotsForSpace(parkingSpaceId);

      // Generate and save new slots
      final newSlots = generateTimeSlots(
        parkingSpaceId: parkingSpaceId,
        availableFrom: availableFrom,
        availableTo: availableTo,
        rentalMode: rentalMode,
      );

      return await saveTimeSlots(newSlots);
    } catch (e) {
      print('Error regenerating time slots: $e');
      return false;
    }
  }

  /// Update slot status to booked (when a driver books it)
  static Future<bool> bookSlot(String slotId) async {
    return await toggleSlotStatus(slotId, ParkingTimeSlotStatus.booked);
  }

  /// Check if any time slots exist for a parking space (for debugging)
  static Future<bool> hasTimeSlots(String parkingSpaceId) async {
    try {
      print(
        '🔍 ParkingTimeSlotService: Checking if time slots exist for parking space: $parkingSpaceId',
      );

      final response = await _supabase
          .from('parking_time_slots')
          .select('id')
          .eq('parking_space_id', parkingSpaceId)
          .limit(1);

      final hasSlots = (response as List).isNotEmpty;
      print('🔍 ParkingTimeSlotService: Time slots exist: $hasSlots');

      return hasSlots;
    } catch (e) {
      print('❌ ParkingTimeSlotService: Error checking time slots: $e');
      return false;
    }
  }

  /// Get all time slots for a parking space (regardless of status) for debugging
  static Future<List<ParkingTimeSlot>> getAllTimeSlots(
    String parkingSpaceId,
  ) async {
    try {
      print(
        '🔍 ParkingTimeSlotService: Fetching ALL time slots for parking space: $parkingSpaceId',
      );

      final response = await _supabase
          .from('parking_time_slots')
          .select()
          .eq('parking_space_id', parkingSpaceId)
          .order('slot_start_time');

      print(
        '🔍 ParkingTimeSlotService: Raw response received: ${response.length} slots',
      );

      final slots = (response as List)
          .map((data) => ParkingTimeSlot.fromJson(data))
          .toList();

      print(
        '🔍 ParkingTimeSlotService: Successfully parsed ${slots.length} slots',
      );

      // Log status breakdown
      final statusCounts = <String, int>{};
      for (final slot in slots) {
        statusCounts[slot.status.value] =
            (statusCounts[slot.status.value] ?? 0) + 1;
      }
      print('🔍 ParkingTimeSlotService: Status breakdown: $statusCounts');

      return slots;
    } catch (e) {
      print('❌ ParkingTimeSlotService: Error fetching all time slots: $e');
      return [];
    }
  }

  /// Get active (bookable) slots for a parking space
  /// If no slots exist, automatically generate them
  static Future<List<ParkingTimeSlot>> getActiveSlots(
    String parkingSpaceId,
  ) async {
    try {
      print(
        '🔍 ParkingTimeSlotService: Fetching active slots for parking space: $parkingSpaceId',
      );

      final response = await _supabase
          .from('parking_time_slots')
          .select()
          .eq('parking_space_id', parkingSpaceId)
          .eq('status', 'active')
          .order('slot_start_time');

      print(
        '🔍 ParkingTimeSlotService: Raw response received: ${response.length} slots',
      );

      final slots = (response as List)
          .map((data) => ParkingTimeSlot.fromJson(data))
          .toList();

      print(
        '🔍 ParkingTimeSlotService: Successfully parsed ${slots.length} slots',
      );

      // If no slots exist, try to generate them automatically
      if (slots.isEmpty) {
        print(
          '🔍 ParkingTimeSlotService: No slots found, attempting to generate them...',
        );
        try {
          // Get parking space details to generate slots
          final spaceResponse = await _supabase
              .from('parking_spaces')
              .select('available_from, available_to')
              .eq('id', parkingSpaceId)
              .single();

          if (spaceResponse != null) {
            final availableFrom = TimeOfDay(
              hour: int.parse(spaceResponse['available_from'].split(':')[0]),
              minute: int.parse(spaceResponse['available_from'].split(':')[1]),
            );
            final availableTo = TimeOfDay(
              hour: int.parse(spaceResponse['available_to'].split(':')[0]),
              minute: int.parse(spaceResponse['available_to'].split(':')[1]),
            );

            print(
              '🔍 ParkingTimeSlotService: Generating slots from $availableFrom to $availableTo',
            );

            final newSlots = generateTimeSlots(
              parkingSpaceId: parkingSpaceId,
              availableFrom: availableFrom,
              availableTo: availableTo,
              rentalMode: 'hourly',
            );

            if (newSlots.isNotEmpty) {
              await saveTimeSlots(newSlots);
              print(
                '🔍 ParkingTimeSlotService: Generated and saved ${newSlots.length} new slots',
              );

              // Fetch the newly created slots
              final newResponse = await _supabase
                  .from('parking_time_slots')
                  .select()
                  .eq('parking_space_id', parkingSpaceId)
                  .eq('status', 'active')
                  .order('slot_start_time');

              final newSlotsList = (newResponse as List)
                  .map((data) => ParkingTimeSlot.fromJson(data))
                  .toList();

              print(
                '🔍 ParkingTimeSlotService: Now have ${newSlotsList.length} active slots',
              );
              return newSlotsList;
            }
          }
        } catch (generateError) {
          print(
            '❌ ParkingTimeSlotService: Error generating slots: $generateError',
          );
        }
      }

      return slots;
    } catch (e) {
      print('❌ ParkingTimeSlotService: Error fetching active slots: $e');
      return [];
    }
  }
}
